version: '3.8'

services:
  aws-tf-01:
    build:
      context: ./build
      args:
        - __WORKSPACE_FOLDER=${WORKSPACE_FOLDER}
    volumes:
      - ../../:/${WORKSPACE_FOLDER}/
    command: [ sleep, infinity ]
